apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vue-app-deployment
spec:
  selector:
    matchLabels:
      app: vue-app
  replicas: 1
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app-hello-world
        imagePullPolicy: Never
        image: vue-app-hello-world
        ports:
        - containerPort: 3000
